<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-AU847K4" failures="1" tests="3" name="Default test" time="24.917" errors="0" timestamp="2025-03-07T17:41:49 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="21.178">
    <failure type="java.lang.AssertionError" message="expected [practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/logged-in-successfully/]">
      <![CDATA[java.lang.AssertionError: expected [practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/logged-in-successfully/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at steps.LoginDemo.the_new_page_url_should_contain(LoginDemo.java:36)
at âœ½.the new page URL should contain "practicetestautomation.com/logged-in-successfully/"(file:///C:/Users/DELL/eclipse-workspace/cucumberproject/src/test/resources/feature/logindemo.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="21.253"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="21.299"/>
</testsuite> <!-- Default test -->
