<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-AU847K4" failures="1" tests="3" name="runners.TestRunner" time="63.730" errors="0" timestamp="2025-03-07T17:41:49 IST" skipped="0">
  <testcase classname="runners.TestRunner" name="runScenario" time="21.299"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="21.178">
    <failure message="expected [practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/logged-in-successfully/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/logged-in-successfully/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at steps.LoginDemo.the_new_page_url_should_contain(LoginDemo.java:36)
at âœ½.the new page URL should contain "practicetestautomation.com/logged-in-successfully/"(file:///C:/Users/DELL/eclipse-workspace/cucumberproject/src/test/resources/feature/logindemo.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="21.253"/>
  <system-out/>
</testsuite> <!-- runners.TestRunner -->
